name: Ms Ellie's Wine
address1: 
address2: 
phone: 
email: 
fax: 
lat: 
lng: 
mapzoom: 13
version: 3.0.3
permalink: pretty
excerpt_separator: ///
collections:
  main-pages:
    output: true
  series:
    output: true
  authors: